### ISSUE TITLE
It seems it does not work right now. 

### ISSUE THREAD

**Issue by sotayamashita** [pr-triage/app#149]
I have not changed the code but it seems it does not work.
I apologize for the inconvenience. :bow: :bow:

**Comment by sotayamashita** [comment]
```
07:35:33.481Z ERROR probot: this.github.pullRequests.getReviews is not a function
  TypeError: this.github.pullRequests.getReviews is not a function
      at PRTriage._getUniqueReviews (/Users/sotayamashita/Documents/workspace/pr-triage/lib/pr-triage.js:93:39)
      at PRTriage._getState (/Users/sotayamashita/Documents/workspace/pr-triage/lib/pr-triage.js:68:32)
      at PRTriage.triage (/Users/sotayamashita/Documents/workspace/pr-triage/lib/pr-triage.js:37:30)
```

**Comment by sotayamashita** [comment]
https://gist.github.com/sotayamashita/fba096a660cac3ac8fd2d77fb5365253

**Comment by sotayamashita** [comment]
remove `engine` field to use node version glitch prepared.

**Comment by sotayamashita** [comment]
@maestromac 
@kevnm67

i haves fixed the issue. 
Thank you for your patience
