### ISSUE TITLE
A JSON web token could not be decoded

### ISSUE THREAD

**Issue by elsayed-atef** [pr-triage/app#91]
I have created my stand alone deployment for Github Enterprise and I got the following error

```
08:55:33.581Z ERROR event: {"message":"A JSON web token could not be decoded","documentation_url":"https://developer.github.com/enterprise/2.13/v3"} (id=220e4f40-a132-11e8-9db5-d4be22122988)
  HttpError: {"message":"A JSON web token could not be decoded","documentation_url":"https://developer.github.com/enterprise/2.13/v3"}
      at response.text.then.message (/pr-triage/node_modules/@octokit/rest/lib/request/request.js:72:19)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  --
  event: {
    "event": "pull_request_review.submitted",
    "id": "220e4f40-a132-11e8-9db5-d4be22122988",
    "installation": 21,
    "repository": "xxxxxxxxx/yyyyyyyy"
  }
08:55:33.581Z  INFO http: POST / 200 - 141.73 ms (id=220e4f40-a132-11e8-9db5-d4be22122988)
09:01:21.185Z DEBUG github: GitHub request: GET /app/installations - 401 undefined (installation=undefined)
  params: {
    "per_page": 100,
    "baseUrl": "https://github.xxxxx.com/api/v3",
    "request": {
      "timeout": 0
    }
  }

```

**Comment by sotayamashita** [comment]
@sayed24 

Thank you for sharing the information. Unfortunately, we do not support GitHub Enterprise(GHE) now. Do you really want to use this library in GHE?

**Comment by sayed24** [comment]
@sotayamashita Thanks for making it clear. I'm looking forward to use this library it GHE it will enhance our work.

**Comment by sotayamashita** [comment]
@elsayed-atef 

You may be also busy, but I would appreciate if you could contribute it. Thanks in advance. 🙇

**Comment by elsayed-atef** [comment]
@sotayamashita i will raise a PR with the changes. It's working with me now on GHE

**Comment by sotayamashita** [comment]
close because it is merged. #95
